# Terraria - Splitux Handler
# 2D sandbox adventure with native Linux support

name: Terraria
exec: Terraria.bin.x86_64
author: splitux
version: "1.1"
info: |
  Terraria co-op splitscreen support.
  Native Linux game using Goldberg Steam Emulator for LAN multiplayer.
spec_ver: 3
steam_appid: 105600
backend: goldberg
pause_between_starts: 3.0

goldberg_settings:
  force_lobby_type.txt: "2"
  invite_all.txt: ""
